#:schema https://globusmedical.github.io/schemas/grab/grab.toml.v1.schema.json

[project]
name = "grpc-armv7l-linux-musleabihf"
edition = 1

[defaults]
registry = "soup-archives"

[registry.soup-archives]
url.base = "s3://globus-soup-archives"

[collections.grpc]
registry = "soup-archives"

[collections.grpc.members]
grpc-armv7l-unknown-linux-musleabihf = { version = "1.71.0", strip_single_root = true }
